name: SnaGCapture
options:
  bundleIdPrefix: uk.kjdev
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.10"
    MARKETING_VERSION: "0.1"
    CURRENT_PROJECT_VERSION: "1"

targets:
  SnaGCapture:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: SnaGCapture
        excludes:
          - "**/.DS_Store"
    info:
      path: SnaGCapture/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.kjdev.SnaGCapture
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        TARGETED_DEVICE_FAMILY: "1,2,6"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO

  SnaGCaptureTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources:
      - SnaGCaptureTests
    dependencies:
      - target: SnaGCapture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.kjdev.SnaGCaptureTests

  SnaGCaptureUITests:
    type: bundle.ui-testing
    platform: [iOS, macOS]
    sources:
      - SnaGCaptureUITests
    dependencies:
      - target: SnaGCapture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.kjdev.SnaGCaptureUITests
